spring.application.name=rest-client
server.port=8080

spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.url=jdbc:mysql://localhost:10000/sg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Email Setting (Gmail 기준)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kjallq@gmail.com
spring.mail.password=itca cohr kcps dxgh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true




# session check min time setting ok
server.servlet.session.timeout=30m